// Generated by CoffeeScript 1.3.3
(function() {
  "use strict";

  $(function() {
    return $(".block-label").click(function() {
      return $(this).toggleClass("block-label-collapsed").parent().siblings("section").first().toggleClass("collapsed");
    });
  });

}).call(this);
